import re

# Shared UUID regex — used across routers and tasks for path/id validation.
# Lowercase hex only; all UUIDs generated by uuid.uuid4() use this format.
UUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
