#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import os
import bpy
from bpy.props import StringProperty

from . import constants as const


class _WebPrefs:
    """Minimal preferences object used in headless/web mode.

    Reads configuration from environment variables so no Blender
    AddonPreferences infrastructure is needed.
    """

    @property
    def default_export_folder(self):
        return os.environ.get('TP3D_OUTPUT_DIR', '/data/outputs')

    @property
    def openTopographyApiKey(self):
        return os.environ.get('TP3D_OPENTOPOGRAPHY_KEY', '')


class TP3D_AddonPreferences(bpy.types.AddonPreferences):
    bl_idname = __package__

    default_export_folder: StringProperty(
        name="Default Export Folder",
        description="Default folder used when exporting STL / OBJ / 3MF files",
        default="",
        subtype='DIR_PATH',
    )  # type: ignore

    openTopographyApiKey: StringProperty(
        name="OpenTopography API Key",
        description="API key from portal.opentopography.org — free registration required for most datasets",
        default="",
    )  # type: ignore

    def draw(self, context):
        from . import temp
        layout = self.layout

        # Premium status
        box = layout.box()
        row = box.row()
        row.label(text="Premium Version:" if temp.PREMIUMVERSION else "Free Version", icon='CHECKMARK' if temp.PREMIUMVERSION else 'X')

        layout.separator()

        # OpenTopography API Key
        layout.label(text="OpenTopography API Key:", icon='INTERNET')
        layout.prop(self, "openTopographyApiKey", text="")
        if not self.openTopographyApiKey:
            layout.label(text="Required for most datasets — free at portal.opentopography.org", icon='ERROR')

        layout.separator()

        # Export
        layout.label(text="Export Settings:", icon='EXPORT')
        layout.prop(self, "default_export_folder")

        layout.separator()

        # Updates
        from . import updater
        layout.label(text="Updates:", icon='FILE_REFRESH')
        box = layout.box()
        current_str = ".".join(str(x) for x in const.ADDON_VERSION)

        if updater.status == "idle":
            row = box.row(align=True)
            row.label(text=f"Current version: v{current_str}", icon='INFO')
            row.operator("tp3d.check_update", text="Check for Updates", icon='FILE_REFRESH')

        elif updater.status == "checking":
            box.label(text="Checking for updates...", icon='TIME')

        elif updater.status == "up_to_date":
            latest_str = ".".join(str(x) for x in updater.latest_version)
            row = box.row(align=True)
            row.label(text=f"Up to date  (v{latest_str})", icon='CHECKMARK')
            row.operator("tp3d.check_update", text="", icon='FILE_REFRESH')

        elif updater.status == "update_available":
            latest_str = ".".join(str(x) for x in updater.latest_version)
            row = box.row(align=True)
            row.label(text=f"Update available: v{latest_str}  (current: v{current_str})", icon='ERROR')
            row.operator("tp3d.check_update", text="", icon='FILE_REFRESH')
            col = box.column()
            col.scale_y = 1.3
            col.operator("tp3d.install_update", text=f"Download & Install v{latest_str}", icon='IMPORT')
            box.label(text="Blender must be restarted after installing.", icon='INFO')

        elif updater.status == "error":
            row = box.row(align=True)
            msg = updater.error_message[:60] + ("..." if len(updater.error_message) > 60 else "")
            row.label(text=f"Check failed: {msg}", icon='CANCEL')
            row.operator("tp3d.check_update", text="Retry", icon='FILE_REFRESH')

        layout.separator()


def get_prefs():
    """Convenience helper — returns the AddonPreferences instance.

    In headless/web mode (TP3D_HEADLESS env var set) returns a lightweight
    _WebPrefs object backed by environment variables instead of Blender's
    addon preferences system.
    """
    if os.environ.get('TP3D_HEADLESS'):
        return _WebPrefs()
    return bpy.context.preferences.addons[__package__].preferences
