#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import os

ADDON_NAME = "TrailPrint3D"
ADDON_VERSION = (3, 0, 8)
required_blender_version = (4, 5, 0)

R = 6371.0  # Earth radius in kilometers

WATER_MAXSIZE = 5000
FOREST_MAXSIZE = 1000
SCREE_MAXSIZE = 1000
CITY_MAXSIZE = 1000
GREENSPACE_MAXSIZE = 50
FARMLAND_MAXSIZE = 1000
GLACIER_MAXSIZE = 1000
BUILDINGS_MAXSIZE = 30
ROADS_MAXSIZE = 500
STREETS_MAJOR_ONLY_THRESHOLD = 100   # above this mapsize: motorway+trunk only
STREETS_PRIMARY_THRESHOLD = 40       # above this mapsize: + primary+secondary

_elevation_cache = {}
specialCollection = []

# ---------------------------------------------------------------------------
# Path resolution: use TP3D_DATA_DIR env var in headless/web mode, otherwise
# fall back to bpy.utils.user_resource('CONFIG') in the normal Blender addon.
# ---------------------------------------------------------------------------

_data_dir = os.environ.get('TP3D_DATA_DIR')

if _data_dir:
    _config_base = _data_dir
else:
    try:
        import bpy
        _config_base = bpy.utils.user_resource('CONFIG')
    except Exception:
        _config_base = os.path.expanduser('~/.config/blender')

# Define a path to store the counter data
counter_file = os.path.join(_config_base, "api_request_counter.json")

#Set up a folder that holds all Cache Data
cache_dir = os.path.join(_config_base, "TrailPrint3D_Cache")

elevation_cache_file = os.path.join(_config_base, "TrailPrint3D_Cache", "elevation_cache.json")

# Set up a cache directory for Terrarium tiles
terrarium_cache_dir = os.path.join(_config_base, "TrailPrint3D_Cache", "terrarium_cache")

# Set up a cache for Overpass Files
overpass_cache_dir = os.path.join(_config_base, "TrailPrint3D_Cache", "overpass_cache")

#Set up a folder for Presets
preset_dir = os.path.join(_config_base, "TP3D-presets")


def _ensure_dirs():
    """Create addon cache/preset directories. Call from register() only."""
    os.makedirs(cache_dir, exist_ok=True)
    os.makedirs(terrarium_cache_dir, exist_ok=True)
    os.makedirs(overpass_cache_dir, exist_ok=True)
    os.makedirs(preset_dir, exist_ok=True)



